### ISSUE TITLE
Question: Vision of the project?

### ISSUE THREAD

**Issue by zakaluka** [AnthonyLloyd/Fsion#2]
Hello,

I am very interested in something like Fsion and excited that you've started this project.  I am working with a couple of systems that either already use or could benefit strongly from EAVT-type architectures for certain parts (for me, that essentially means the benefits of EAV with built-in auditing and history support).

I am curious about your vision with this project.  What are your goals / objectives with Fsion?  For example:

- Do you see Fsion as a replacement for the normal DB modeling activity that occurs for databases (i.e. basically replace DB modeling with good data structure design without worrying about how that data is being maintained)?
- Are you aiming for it to be a backend-agnostic system, targeting a relational database, targeting some other existing backend, or something else (e.g. flat files)?
    - From a performance perspective, it may make sense to target a single (or specific) backend and customize to it.  
    - You mention Datomic, which is closely coupled with AWS.  Do you think something like this (tie-in with 1 or a small group of vendors) will be required eventually?
- What use cases are you looking to support?  Is it a general EAV or targeted at any specific industries?  
- Is there a reference system on which you are basing this project?  You mentioned that this is a pattern you see often in your work.  
- You mention in-memory querying to increase performance.  Does that refer to some type of parent-worker relationship between data stores (assuming most larger systems cannot hold the entire data set in a single client's memory)?
- Etc.

And, I guess one final overarching question - since there are a number of alternatives to EAV systems today (whether that's NoSQL databases, JSON blobs, native support for sparse data in relational DBs, etc.), where do you see Fsion fitting into this space?

In addition to these overarching questions, I am also curious whether you have any links for some of the terminology that you use.  For example, I'm not totally sure what a "compressed time-series" is.  Is it referring to a way to store the changes to an attribute's value over time more efficiently?

Thank you.

P.S.: I do not intend for the above to come across as an attack or questioning of the goals of this project.  I'm just curious to learn more because this is the only native F# project I've seen that is trying to tackle this issue.

**Comment by AnthonyLloyd** [comment]
Yes I do see Fsion as a general replacment for a database. Firstly, I believe full audit should be part of all database applications. We should not be deciding what data we destroy given how cheap local and cloud disk space is. Secondly, I believe bringing the database closer to the server and users opens up an exciting set of new possibilities, from using function attributes over saving duplicate data, to users being able to help extend the schema.

It will be backend-agnostic to quite a degree. These backend APIs are starting to slowly come together (DataSeriesCache, StringCache, TransactionLog). The serialization is built in, so these APIs are primarily about storing byte arrays to memory, disk and cloud with some concurrency constraints. DataSeriesCache would be stored in memory and local disk (possibly Redis/memcached also). Transactionlog could be any cloud storage.

EAVT databases and Fsion do have some features that give quite an advantage over traditional databases for some industries. Firstly because the schema is so flexible ([universal schema](https://docs.datomic.com/cloud/whatis/data-model.html)) it is particularly good when companies merge two or more databases. Secondly some industries like finance use bi-temporal data a lot in their business logic. Time series of prices or prior time period adjustments and period calculations. Thirdly, also particularly in finance a large number of calculations can be specified as a set declarative functions e.g. unit cost, realised pl, period returns, even risk. Defining these calculations as a set of function attributes with more powerful aggregation results in a multi dimensional version of excel that is not only more useful for developers but also reduces the need to save calculations results which are essentially duplicate data which bring a whole host of refresh and reconciliation problems.

Fsion is inspired by Datomic, [simdcomp](https://github.com/lemire/simdcomp) and other systems I have worked on in my career. It doesn't have a single reference system and has some key differences to Datomic.

Fsion is designed to fit the database either entirely in memory or memory and local disk using [FASTER](https://github.com/Microsoft/FASTER). By reducing duplicate data, performing cheap calculations on the fly and using in memory compression this is possible for most database systems even though a lot of developers don't think this is the case ([data-first architecture](http://anthonylloyd.github.io/blog/2018/02/01/architecture-data-first)).

Thanks for your questions, they were good. Please let me know if anything isn't clear or if you have further questions. I may add them to the readme or a FAQ.

**Comment by zakaluka** [comment]
@AnthonyLloyd Thank you very much for the detailed answer.  I couldn't agree more with some of your statements, such as building audit into all database applications.  I am definitely looking forward to how this project progresses.  

Once you get to the point that you want contributions from the community, I'd be happy to try and help if I can.

**Comment by AnthonyLloyd** [comment]
Thanks. I will be providing a status update mid December as part of F# advent.
